INSERT INTO Songs (Title, BandName) VALUES
('Aint Life Grand', 'Kane Brown'),
('Old Town Road', 'Lil Nas X'),
('Better Now', 'Post Malone'),
('Congratulations', 'Post Malone'),
('This Aint A Scene', 'Fall Out Boy'),
('Thanks For the Memories', 'Fall Out Boy'),
('Flowers', 'Miley Cyrus'),
('Kill Bill', 'SZA'),
('Love Again', 'The Kid LARIO'),
('Gossip', 'Maneskin'),
('Im not here to make friends', 'Sam Smith'),
('Giddy Up', 'Shania Twain'),
('Trustfall', 'P!nk'),
('Queen of Kings', 'Alessandra'),
('F64', 'Ed Sheeran'),
('Voices', 'KSI, Oliver Tree'),
('I Want It That Way', 'Back Street Boys'),
('I Will Survive', 'Gloria Gaynor'),
('Bohemian Rhapsody', 'Queen'),
('Say It Ain\'t So', 'Weezer'),
('Love Shack', 'B-52s'),
('Life\'s A Mess II', 'Juice WRLD'),
('Circles', 'Post Malone'),
('White Iverson', 'Post Malone'),
('Heroes', 'David Bowie'), 
('Transformer', 'Lou Reed'), 
('Under Pressure', 'Queen & David Bowie'), 
('Lust for Life', 'Iggy Pop'), 
('Raw Power', 'Iggy and The Stooges'),
('Heat Waves', 'Glass Animals');

INSERT INTO Contributors (Name)
VALUES
('Kane Brown'),
('Lil Nas X'),
('Billy Ray Cyrus'),
('YoungKio'),
('Post Malone'),
('Frank Dukes'),
('Quavo'),
('Fall Out Boy'),
('Pete Wentz'),
('Patrick Stump'),
('Joe Trohman'),
('Andy Hurley'),
('Neal Avron'),
('Babyface'),
('Miley Cyrus'),
('Kid Harpoon'),
('Tyler Johnson'),
('SZA'),
('Solana Rowe'),
('Carter Lang'),
('The Kid LARIO'),
('Charlton Howard'),
('Omer Fedi'),
('Maneskin'),
('Tom Morello'),
('Sam Smith'),
('Calvin Harris'),
('Shania Twain'),
('David Stewart'),
('P!nk'),
('Fred Again'),
('Alessandra Mele'),
('Ed Sheeran'),
('Fred'),
('Oliver Tree'),
('Olajide Olatunji'),
('Digital Farm Animals'),
('Back Street Boys'),
('Andreas Carlsson'),
('Max Martin'),
('Kristian Lundin'),
('Gloria Gaynor'),
('Freddier Perren'),
('Dino Fekaris'),
('Queen'),
('Freddie Mercury'),
('Roy Thomas Baker'),
('Weezer'),
('Rivers Cuomo'),
('Ric Ocasek'),
('B-52s'),
('Don Was'),
('Juice WRLD'),
('Jarad Higgins'),
('Rick Rubin'),
('Louis Bell'),
('David Bowie'),
('Brian Eno'),
('Tony Visconti'),
('Lou Reed'),
('Mick Ronson'),
('Reinhold Mack'),
('Iggy Pop'),
('Hunt Sales'),
('James Williamson'),
('Glass Animals'),
('Dave Bayley');





