CREATE TABLE SongContributors (
  SongID INT,
  ContributorID INT,
  Role VARCHAR(255),
  PRIMARY KEY (SongID, ContributorID),
  FOREIGN KEY (SongID) REFERENCES Songs(SongID),
  FOREIGN KEY (ContributorID) REFERENCES Contributors(ContributorID)
);


INSERT INTO SongContributors (SongID, ContributorID, Role) VALUES 
(1, 1, 'Performer and Songwriter'), 
(2, 2, 'Performer and Songwriter'), (2, 3, 'Performer'), (2, 4, 'Producer'),
(3, 5, 'Performer and Songwriter'), (3, 6, 'Producer'),
(4, 5, 'Performer and Songwriter'), (4, 7, 'Performer and Songwriter'), (4, 6, 'Songwriter and Producer'),
(5, 8, 'Performers'), (5, 9, 'Bass Guitarist Singer and Songwriter'), (5, 10, 'Guitarist Singer and Songwriter'), (5, 11, 'Guitarist Singer and Songwriter'), (5, 12, 'Drummer Singer and Songwriter'), (5, 13, 'Producer'),
(6, 8, 'Performers'), (6, 9, 'Bass Guitarist Singer and Songwriter'), (6, 10, 'Guitarist Singer and Songwriter'), (6, 11, 'Guitarist Singer and Songwriter'), (6, 12, 'Drummer Singer and Songwriter'), (6, 14, 'Producer'),
(7, 15, 'Singer and Songwriter'), (7, 16, 'Producer'), (7, 17, 'Producer'),
(8, 18, 'Performer'), (8, 19, 'Singer and Songwriter'), (8, 20, 'Producer'),
(9, 21, 'Performer'), (9, 22, 'Singer and Songwriter'), (9, 23, 'Producer'),
(10, 24, 'Performers Songwriters and Producers'), (10, 25, 'Performer and Songwriter'),
(11, 26, 'Singer and Songwriter'), (11, 27, 'Producer'),
(12, 28, 'Singer and Songwriter'), (12, 29, 'Songwriter and Producer'),
(13, 30, 'Singer and Songwriter'), (13, 31, 'Producer'),
(14, 32, 'Singer and Songwriter'),
(15, 33, 'Singer and Songwriter'), (15, 34, 'Producer'),
(16, 35, 'Singer and Songwriter'), (16, 36, 'Singer and Songwriter'), (16, 37, 'Producer'),
(17, 38, 'Performers'), (17, 39, 'Singer and Songwriter'), (17, 40, 'Singer Songwriter and Producer'), (17, 41, 'Producer'),
(18, 42, 'Performer'), (18, 43, 'Songwriter and Producer'), (18, 44, 'Songwriter and Producer'),
(19, 45, 'Performers and Producers'), (19, 46, 'Songwriter'), (19, 47, 'Producer'),
(20, 48, 'Performers'), (20, 49, 'Songwriter'), (20, 50, 'Producer'),
(21, 51, 'Performers and Songwriters'), (21, 52, 'Producer'),
(22, 53, 'Performers'), (22, 54, 'Performer and Songwriter'), (22, 55, 'Producer'),
(23, 5, 'Performer and Songwriter'), (23, 56, 'Producer'), (23, 6, 'Producer'),
(24, 5, 'Performer and Songwriter'), 
(25, 57, 'Performer and Songwriter'), (25, 58, 'Songwriter and Producer'), (25, 59, 'Producer'),
(26, 60, 'Performer and Songwriter'), (26, 61, 'Performer and Producer'), (26, 57, 'Producer'),
(27, 45, 'Performers and Producers'), (27, 57, 'Performer and Songwriter'), (27, 62, 'Producer'),
(28, 63, 'Performer and Songwriter'), (28, 57, 'Songwriter and Producer'), (28, 64, 'Performer and Producer'),
(29, 63, 'Performer and Songwriter'), (29, 65, 'Performer and Songwriter'), (29, 57, 'Producer'),
(30, 66, 'Performers and Songwriters'), (30, 67, 'Producer');