CREATE TABLE Users (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255)
);

CREATE TABLE Songs (
  SongID INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(255),
  BandName VARCHAR(255)
);

CREATE TABLE Requests (
  RequestID INT PRIMARY KEY AUTO_INCREMENT,
  SongID INT,
  UserID INT,
  Time DATETIME,
  AmountPaid DECIMAL(10,2),
  QueueType VARCHAR(255),
  RequestIndex INT,
  FOREIGN KEY (SongID) REFERENCES Songs(SongID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE SongVersions (
  VersionID INT PRIMARY KEY AUTO_INCREMENT,
  SongID INT,
  KaraokeFile VARCHAR(255),
  Description TEXT,
  FOREIGN KEY (SongID) REFERENCES Songs(SongID)
);

CREATE TABLE Contributors (
  ContributorID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255)
);

CREATE TABLE SongContributors (
  SongID INT,
  ContributorID INT,
  Role VARCHAR(255),
  PRIMARY KEY (SongID, ContributorID),
  FOREIGN KEY (SongID) REFERENCES Songs(SongID),
  FOREIGN KEY (ContributorID) REFERENCES Contributors(ContributorID)
);
